/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:259537:
  appc.background(230);
} //_CODE_:window1:259537:

public void spawnCar_click1(GButton source, GEvent event) { //_CODE_:spawnCar:541196:
  spawnCar();
} //_CODE_:spawnCar:541196:

public void time_change1(GSlider source, GEvent event) { //_CODE_:timeslider:567562:
  time = timeslider.getValueI();
  redraw();
} //_CODE_:timeslider:567562:

public void pause_click1(GButton source, GEvent event) { //_CODE_:pause:848946:
   paused = !paused;

  if (pause.getText().equals("Pause")) {
    pause.setText("Resume");
    pause.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  } else {
    pause.setText("Pause"); 
    pause.setLocalColorScheme(GCScheme.RED_SCHEME);
  }
} //_CODE_:pause:848946:

public void clear_click1(GButton source, GEvent event) { //_CODE_:clear:633085:
  setupVehicleArrays();
  totalCollisions = 0;
} //_CODE_:clear:633085:

public void speed_change1(GSlider source, GEvent event) { //_CODE_:speed:759106:
  cSpeed = speed.getValueI();
} //_CODE_:speed:759106:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 400, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  spawnCar = new GButton(window1, 290, 120, 28, 28);
  spawnCar.setIcon("car_icon.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  spawnCar.addEventHandler(this, "spawnCar_click1");
  spawnCarText = new GLabel(window1, 260, 90, 80, 20);
  spawnCarText.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  spawnCarText.setText("Spawn Car");
  spawnCarText.setOpaque(false);
  timeslider = new GSlider(window1, 20, 110, 176, 50, 10.0);
  timeslider.setShowValue(true);
  timeslider.setLimits(8, 0, 24);
  timeslider.setNbrTicks(24);
  timeslider.setStickToTicks(true);
  timeslider.setShowTicks(true);
  timeslider.setNumberFormat(G4P.INTEGER, 0);
  timeslider.setLocalColorScheme(GCScheme.RED_SCHEME);
  timeslider.setOpaque(false);
  timeslider.addEventHandler(this, "time_change1");
  label1 = new GLabel(window1, 60, 80, 80, 30);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Time");
  label1.setOpaque(false);
  pause = new GButton(window1, 130, 40, 153, 30);
  pause.setText("Pause");
  pause.setLocalColorScheme(GCScheme.RED_SCHEME);
  pause.addEventHandler(this, "pause_click1");
  clear = new GButton(window1, 160, 340, 80, 30);
  clear.setText("Clear Cars");
  clear.addEventHandler(this, "clear_click1");
  speed = new GSlider(window1, 100, 230, 215, 65, 10.0);
  speed.setShowValue(true);
  speed.setLimits(5, 5, 20);
  speed.setNbrTicks(4);
  speed.setStickToTicks(true);
  speed.setNumberFormat(G4P.INTEGER, 0);
  speed.setOpaque(false);
  speed.addEventHandler(this, "speed_change1");
  speedlabel = new GLabel(window1, 170, 210, 80, 20);
  speedlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  speedlabel.setText("Car Speed");
  speedlabel.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton spawnCar; 
GLabel spawnCarText; 
GSlider timeslider; 
GLabel label1; 
GButton pause; 
GButton clear; 
GSlider speed; 
GLabel speedlabel; 
